# Generated by Django 2.2.6 on 2020-07-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('leader', models.CharField(max_length=20)),
                ('telephone', models.IntegerField(default=0)),
            ],
        ),
    ]
