# Generated by Django 2.2.6 on 2020-07-21 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='handle_content',
            field=models.CharField(default='', max_length=500, null=True),
        ),
    ]
